### ISSUE TITLE
node.js version

### ISSUE THREAD

**Issue by bebeboy** [marcoraddatz/homebridge-docker#10]
I have a problem while startup the npm - homebridge-broadlink-rm. The Author suggested me to upgrade node to the latest version.  Could you please share me some hints?  Sorry that I am not good at programming stuff.

**Comment by marcoraddatz** [comment]
You could upgrade to latest node via using the `install.sh`. This link might help: https://davidwalsh.name/upgrade-nodejs

**Comment by marcoraddatz** [comment]
Oops. Hit the wrong button!

**Comment by bebeboy** [comment]
Thanks for your reply.  While trying to install the latest node.js.  I do a clean re-install of homebridge and found two error messages I haven't seen before.  Is that something I should look at?

[Second part error message]
2017-04-11 10:21:07	stdout	    at Function.Module._load (module.js:424:3)
2017-04-11 10:21:07	stdout	    at tryModuleLoad (module.js:432:12)
2017-04-11 10:21:07	stdout	    at Module.load (module.js:473:32)
2017-04-11 10:21:07	stdout	    at Object.Module._extensions..js (module.js:565:10)
2017-04-11 10:21:07	stdout	    at Module._compile (module.js:556:32)
2017-04-11 10:21:07	stdout	    at Object.<anonymous> (/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/util/encryption.js:3:18)
2017-04-11 10:21:07	stdout	    at require (internal/module.js:20:19)
2017-04-11 10:21:07	stdout	    at Module.require (module.js:483:17)
2017-04-11 10:21:07	stdout	    at Function.Module._load (module.js:403:25)
2017-04-11 10:21:07	stdout	    at Function.Module._resolveFilename (module.js:455:15)
2017-04-11 10:21:07	stdout	Error: Cannot find module 'curve25519-n'
2017-04-11 10:21:07	stdout	
2017-04-11 10:21:07	stdout	    ^
2017-04-11 10:21:07	stdout	    throw err;
2017-04-11 10:21:07	stdout	module.js:457

.....
[First part error message]
2017-04-11 10:19:15	stdout	[0m[37;40mnpm[0m [0m[31;40mERR![0m [0m[35mcode[0m 1
2017-04-11 10:19:15	stdout	[0m[37;40mnpm[0m [0m[31;40mERR![0m[35m[0m     /root/.homebridge/npm-debug.log
2017-04-11 10:19:15	stdout	[37;40mnpm[0m [0m[31;40mERR![0m[35m[0m Please include the following file with any support request:
2017-04-11 10:19:15	stdout	[0m
2017-04-11 10:19:15	stdout	[0m[37;40mnpm[0m [0m[31;40mERR![0m[35m[0m     <https://github.com/npm/npm/issues>
2017-04-11 10:19:15	stdout	[0m[37;40mnpm[0m [0m[31;40mERR![0m[35m[0m If you need help, you may report this error at:
2017-04-11 10:19:15	stdout	[0m[37;40mnpm[0m [0m[31;40mERR![0m[35m[0m 
2017-04-11 10:19:15	stdout	[37;40mnpm[0m [0m[31;40mERR![0m[35m[0m EXDEV: cross-device link not permitted, rename '/usr/lib/node_modules/homebridge/node_modules/mkdirp' -> '/usr/lib/node_modules/homebridge/node_modules/.mkdirp.DELETE'
2017-04-11 10:19:15	stdout	[0m
2017-04-11 10:19:15	stdout	[0m[37;40mnpm[0m [0m[31;40mERR![0m [0m[35msyscall[0m rename
2017-04-11 10:19:15	stdout	[0m[37;40mnpm[0m [0m[31;40mERR![0m [0m[35merrno[0m -18
2017-04-11 10:19:15	stdout	[0m[37;40mnpm[0m [0m[31;40mERR![0m [0m[35mcode[0m EXDEV
2017-04-11 10:19:15	stdout	[0m[37;40mnpm[0m [0m[31;40mERR![0m [0m[35mpath[0m /usr/lib/node_modules/homebridge/node_modules/mkdirp
2017-04-11 10:19:15	stdout	[0m[37;40mnpm[0m [0m[31;40mERR![0m [0m[35mnpm [0m v3.10.3
2017-04-11 10:19:15	stdout	[0m[37;40mnpm[0m [0m[31;40mERR![0m [0m[35mnode[0m v6.7.0
2017-04-11 10:19:15	stdout	[0m[37;40mnpm[0m [0m[31;40mERR![0m [0m[35margv[0m "/usr/bin/nodejs" "/usr/bin/npm" "update" "-g" "homebridge"
2017-04-11 10:19:15	stdout	[37;40mnpm[0m [0m[31;40mERR![0m[35m[0m Linux 3.10.102

**Comment by Demonderik** [comment]
Hi Marco!

The similar situation here. Homebridge won't work from yesterday.
I attached my config files and log.

[homebridge.zip](https://github.com/marcoraddatz/homebridge-docker/files/912997/homebridge.zip)

[homebridge.html.zip](https://github.com/marcoraddatz/homebridge-docker/files/912982/homebridge.html.zip)

**Comment by marcoraddatz** [comment]
@bebeboy The auto-update might have broken Homebridge. Can you verify, if the error still appears in version 2.2?

@Demonderik Config seems to be ok so far. Can you please also check version 2.2?

**Comment by Demonderik** [comment]
Marco,
Version 2.2 runs fine! Thank you.

**Comment by bebeboy** [comment]
It disappeared.  Thank you so much.  Working on node.js update :)

**Comment by marcoraddatz** [comment]
I might update the node version soon, since the nodesource project seem to be dead. Considering official node to be used with an alpine image, but closing the ticket for now 😉

**Comment by bebeboy** [comment]
I can  install the latest node.js through install.sh, but homebridge crashed then.  Maybe I wait for your next version then.  Cheers.

date	stream	content
2017-04-12 18:51:18	stdout	    at Module.load (module.js:488:32)
2017-04-12 18:51:18	stdout	    at Object.Module._extensions..js (module.js:580:10)
2017-04-12 18:51:18	stdout	    at Module._compile (module.js:571:32)
2017-04-12 18:51:18	stdout	    at Object.<anonymous> (/usr/lib/node_modules/homebridge/node_modules/mdns/lib/dns_sd.js:24:20)
2017-04-12 18:51:18	stdout	    at require (internal/module.js:20:19)
2017-04-12 18:51:18	stdout	    at Module.require (module.js:498:17)
2017-04-12 18:51:18	stdout	    at Function.Module._load (module.js:439:3)
2017-04-12 18:51:18	stdout	    at tryModuleLoad (module.js:447:12)
2017-04-12 18:51:18	stdout	    at Module.load (module.js:488:32)
2017-04-12 18:51:18	stdout	    at Object.Module._extensions..node (module.js:598:18)
2017-04-12 18:51:18	stdout	the module (for instance, using `npm rebuild` or`npm install`).
2017-04-12 18:51:18	stdout	NODE_MODULE_VERSION 51. Please try re-compiling or re-installing
2017-04-12 18:51:18	stdout	NODE_MODULE_VERSION 48. This version of Node.js requires
2017-04-12 18:51:18	stdout	was compiled against a different Node.js version using
2017-04-12 18:51:18	stdout	Error: The module '/usr/lib/node_modules/homebridge/node_modules/mdns/build/Release/dns_sd_bindings.node'
2017-04-12 18:51:18	stdout	
2017-04-12 18:51:18	stdout	    ^
2017-04-12 18:51:18	stdout	    throw ex;
2017-04-12 18:51:18	stdout	/usr/lib/node_modules/homebridge/node_modules/mdns/lib/dns_sd.js:35
2017-04-12 18:51:08	stdout	
2017-04-12 18:51:08	stdout	  [36m installed[0m : [2mv7.9.0[22m[0m
2017-04-12 18:51:02	stdout	                                                                           0.0%                                                                            ######################################################################## 100.0%
2017-04-12 18:50:10	stdout	  [36m     fetch[0m : [2mhttps://nodejs.org/dist/v7.9.0/node-v7.9.0-linux-x64.tar.gz[22m[0m
2017-04-12 18:50:10	stdout	  [36m     mkdir[0m : [2m/usr/local/n/versions/node/7.9.0[22m[0m
2017-04-12 18:50:08	stdout	  [36m   install[0m : [2mnode-v7.9.0[22m[0m
