### ISSUE TITLE
Got error during Updating Homebridge.

### ISSUE THREAD

**Issue by brianping7** [marcoraddatz/homebridge-docker#11]
I  got this error during container start up. anyone could help?

EXDEV: cross-device link not permitted, rename '/usr/lib/node_modules/homebridge/node_modules/mkdirp' -> '/usr/lib/node_modules/homebridge/node_modules/.mkdirp.DELETE'

**Comment by marcoraddatz** [comment]
What were your previous steps? Does this still apply in version 2.2?

**Comment by brianping7** [comment]
i just pull the latest version from docker ,and try to start it. it failed because the above error.

**Comment by brianping7** [comment]
i will try 2.2 to see if still have the error, thanks.

**Comment by marcoraddatz** [comment]
Might be a plugin then or are you trying to update node?

**Comment by DaveHamilton** [comment]
I'm seeing the same thing.

```2017-04-12 13:41:06	stdout	    at Function.Module._load (module.js:424:3)
2017-04-12 13:41:06	stdout	    at tryModuleLoad (module.js:432:12)
2017-04-12 13:41:06	stdout	    at Module.load (module.js:473:32)
2017-04-12 13:41:06	stdout	    at Object.Module._extensions..js (module.js:565:10)
2017-04-12 13:41:06	stdout	    at Module._compile (module.js:556:32)
2017-04-12 13:41:06	stdout	    at Object.<anonymous> (/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/Accessory.js:1:91)
2017-04-12 13:41:06	stdout	    at require (internal/module.js:20:19)
2017-04-12 13:41:06	stdout	    at Module.require (module.js:483:17)
2017-04-12 13:41:06	stdout	    at Function.Module._load (module.js:403:25)
2017-04-12 13:41:06	stdout	    at Function.Module._resolveFilename (module.js:455:15)
2017-04-12 13:41:06	stdout	Error: Cannot find module 'debug'
2017-04-12 13:41:06	stdout	
2017-04-12 13:41:06	stdout	    ^
2017-04-12 13:41:06	stdout	    throw err;
2017-04-12 13:41:06	stdout	module.js:457
2017-04-12 13:41:06	stdout	Installing plugins from /root/.homebridge/install.sh.
2017-04-12 13:41:06	stdout	[0m/root/.homebridge/package.json not found.
2017-04-12 13:41:06	stdout	[0m[37;40mnpm[0m [0m[31;40mERR![0m [0m[35mcode[0m 1
2017-04-12 13:41:06	stdout	[0m[37;40mnpm[0m [0m[31;40mERR![0m[35m[0m     /root/.homebridge/npm-debug.log
2017-04-12 13:41:06	stdout	[37;40mnpm[0m [0m[31;40mERR![0m[35m[0m Please include the following file with any support request:
2017-04-12 13:41:06	stdout	[0m
2017-04-12 13:41:06	stdout	[0m[37;40mnpm[0m [0m[31;40mERR![0m[35m[0m     <https://github.com/npm/npm/issues>
2017-04-12 13:41:06	stdout	[0m[37;40mnpm[0m [0m[31;40mERR![0m[35m[0m If you need help, you may report this error at:
2017-04-12 13:41:06	stdout	[0m[37;40mnpm[0m [0m[31;40mERR![0m[35m[0m 
2017-04-12 13:41:06	stdout	[37;40mnpm[0m [0m[31;40mERR![0m[35m[0m EXDEV: cross-device link not permitted, rename '/usr/lib/node_modules/homebridge/node_modules/debug' -> '/usr/lib/node_modules/homebridge/node_modules/.debug.DELETE'
2017-04-12 13:41:06	stdout	[0m
2017-04-12 13:41:06	stdout	[0m[37;40mnpm[0m [0m[31;40mERR![0m [0m[35msyscall[0m rename
2017-04-12 13:41:06	stdout	[0m[37;40mnpm[0m [0m[31;40mERR![0m [0m[35merrno[0m -18
2017-04-12 13:41:06	stdout	[0m[37;40mnpm[0m [0m[31;40mERR![0m [0m[35mcode[0m EXDEV
2017-04-12 13:41:06	stdout	[0m[37;40mnpm[0m [0m[31;40mERR![0m [0m[35mpath[0m /usr/lib/node_modules/homebridge/node_modules/debug
2017-04-12 13:41:06	stdout	[0m[37;40mnpm[0m [0m[31;40mERR![0m [0m[35mnpm [0m v3.10.3
2017-04-12 13:41:06	stdout	[0m[37;40mnpm[0m [0m[31;40mERR![0m [0m[35mnode[0m v6.7.0
2017-04-12 13:41:06	stdout	[0m[37;40mnpm[0m [0m[31;40mERR![0m [0m[35margv[0m "/usr/bin/nodejs" "/usr/bin/npm" "update" "-g" "homebridge"
2017-04-12 13:41:06	stdout	[37;40mnpm[0m [0m[31;40mERR![0m[35m[0m Linux 3.10.102
2017-04-12 13:41:06	stdout	
2017-04-12 13:41:06	stdout	`-- (empty)
2017-04-12 13:41:06	stdout	[?25l[[90m..................[0m] - : [32minfo[0m [35musing[0m node@v6.7.0[K [[90m..................[0m] - : [32minfo[0m [35musing[0m node@v6.7.0[K [[90m..................[0m] - : [32minfo[0m [35musing[0m node@v6.7.0[K [[90m..................[0m] - : [32minfo[0m [35musing[0m node@v6.7.0[K [[90m..................[0m] - : [32minfo[0m [35musing[0m node@v6.7.0[K [[90m..................[0m] - : [32minfo[0m [35musing[0m node@v6.7.0[K [[90m..................[0m] - : [32minfo[0m [35musing[0m node@v6.7.0[K [[90m..................[0m] - : [32minfo[0m [35musing[0m node@v6.7.0[K [[90m..................[0m] - : [32minfo[0m [35musing[0m node@v6.7.0[K [[90m..................[0m] - : [32minfo[0m [35musing[0m node@v6.7.0[K [[90m..................[0m] - : [32minfo[0m [35musing[0m node@v6.7.0[K [[90m..................[0m] - : [32minfo[0m [35musing[0m node@v6.7.0[K [[90m..................[0m] - : [32minfo[0m [35musing[0m node@v6.7.0[K [[90m..................[0m] - : [32minfo[0m [35musing[0m node@v6.7.0[K [[90m..................[0m] - : [32minfo[0m [35musing[0m node@v6.7.0[K [[90m..................[0m] - : [32minfo[0m [35musing[0m node@v6.7.0[K [[90m..................[0m] - : [32minfo[0m [35musing[0m node@v6.7.0[K [[90m..................[0m] - : [32minfo[0m [35musing[0m node@v6.7.0[K [[90m..................[0m] - : [32minfo[0m [35musing[0m node@v6.7.0[K [[90m..................[0m] - : [32minfo[0m [35musing[0m node@v6.7.0[K [[90m..................[0m] - : [32minfo[0m [35musing[0m node@v6.7.0[K [[90m..................[0m] - : [32minfo[0m [35musing[0m node@v6.7.0[K [[90m..................[0m] - : [32minfo[0m [35musing[0m node@v6.7.0[K [[90m..................[0m] - : [32minfo[0m [35musing[0m node@v6.7.0[K [[90m..................[0m] - : [32minfo[0m [35musing[0m node@v6.7.0[K [[90m..................[0m] - : [32minfo[0m [35musing[0m node@v6.7.0[K [[90m..................[0m] \ : [32minfo[0m [35musing[0m node@v6.7.0[K [[90m..................[0m] - : [32minfo[0m [35musing[0m node@v6.7.0[K [[90m..................[0m] - : [32minfo[0m [35musing[0m node@v6.7.0[K [[90m..................[0m] | : [32minfo[0m [35musing[0m node@v6.7.0[K [[90m..................[0m] | : [32minfo[0m [35musing[0m node@v6.7.0[K [[90m..................[0m] \ normalizeTree: [7msill[0m [35minstall[0m loadCurrentTree[K [[90m..................[0m] | normalizeTree: [7msill[0m [35minstall[0m loadCurrentTree[K [[7m   [27m[90m...............[0m] / cloneCurrentTree: [7msill[0m [35mcloneCurrentTree[0m Finishing[K [[7m    [27m[90m..............[0m] | loadRequestedDeps: [7msill[0m [35minstall[0m loadAllDepsIntoIdealTree[K [[7m    [27m[90m..............[0m] / loadRequestedDeps: [7msill[0m [35minstall[0m loadAllDepsIntoIdealTree[K [[7m    [27m[90m..............[0m] \ fetchMetadata: [7msill[0m [35mmapToRegistry[0m uri https://registry.n[K [[7m    [27m[90m..............[0m] \ fetchMetadata: [7msill[0m [35mmapToRegistry[0m uri https://registry.n[K [[7m    [27m[90m..............[0m] \ fetchMetadata: [7msill[0m [35mmapToRegistry[0m uri https://registry.n[K [[7m    [27m[90m..............[0m] - fetchMetadata: [7msill[0m [35mmapToRegistry[0m uri https://registry.n[K [[7m    [27m[90m..............[0m] \ fetchMetadata: [7msill[0m [35mmapToRegistry[0m uri https://registry.n[K [[7m    [27m[90m..............[0m] - fetchMetadata: [7msill[0m [35mmapToRegistry[0m uri https://registry.n[K [[7m    [27m[90m..............[0m] - fetchMetadata: [7msill[0m [35mmapToRegistry[0m uri https://registry.n[K [[7m    [27m[90m..............[0m] - fetchMetadata: [7msill[0m [35mmapToRegistry[0m uri https://registry.n[K [[7m    [27m[90m..............[0m] | fetchMetadata: [7msill[0m [35mmapToRegistry[0m uri https://registry.n[K [[7m    [27m[90m..............[0m] | fetchMetadata: [34;40mverb[0m [35mafterAdd[0m /root/.npm/supports-color/2[K [[7m    [27m[90m..............[0m] | fetchMetadata: [34;40mverb[0m [35mafterAdd[0m /root/.npm/ansi-regex/2.1.1[K [[7m     [27m[90m.............[0m] \ fetchMetadata: [7msill[0m [35mmapToRegistry[0m uri https://registry.n[K [[7m     [27m[90m.............[0m] | fetchMetadata: [7msill[0m [35mmapToRegistry[0m uri https://registry.n[K [[7m     [27m[90m.............[0m] / fetchMetadata: [7msill[0m [35mmapToRegistry[0m uri https://registry.n[K [[7m     [27m[90m.............[0m] \ fetchMetadata: [7msill[0m [35mmapToRegistry[0m uri https://registry.n[K [[7m     [27m[90m.............[0m] | fetchMetadata: [7msill[0m [35mmapToRegistry[0m uri https://registry.n[K [[7m     [27m[90m.............[0m] \ fetchMetadata: [7msill[0m [35mmapToRegistry[0m uri https://registry.n[K [[7m     [27m[90m.............[0m] \ fetchMetadata: [7msill[0m [35mmapToRegistry[0m uri https://registry.n[K [[7m     [27m[90m.............[0m] \ fetchMetadata: [7msill[0m [35mmapToRegistry[0m uri https://registry.n[K [[7m     [27m[90m.............[0m] / fetchMetadata: [7msill[0m [35mmapToRegistry[0m uri https://registry.n[K [[7m     [27m[90m.............[0m] / fetchMetadata: [34;40mverb[0m [35mafterAdd[0m /root/.npm/bindings/1.2.1/p[K [[7m     [27m[90m.............[0m] / fetchMetadata: [34;40mverb[0m [35mafterAdd[0m /root/.npm/ms/0.7.2/package[K [[7m     [27m[90m.............[0m] - fetchMetadata: [34;40mverb[0m [35mafterAdd[0m /root/.npm/ms/0.7.2/package[K [[7m     [27m[90m.............[0m] - fetchMetadata: [7msill[0m [35mmapToRegistry[0m uri https://registry.n[K [[7m     [27m[90m.............[0m] - fetchMetadata: [7msill[0m [35mmapToRegistry[0m uri https://registry.n[K [[7m     [27m[90m.............[0m] / fetchMetadata: [7msill[0m [35mmapToRegistry[0m uri https://registry.n[K [[7m     [27m[90m.............[0m] - fetchMetadata: [34;40mverb[0m [35mafterAdd[0m /root/.npm/q/1.1.2/package/[K [[7m     [27m[90m.............[0m] | fetchMetadata: [34;40mverb[0m [35mafterAdd[0m /root/.npm/q/1.1.2/package/[K [[7m      [27m[90m............[0m] | fetchMetadata: [34;40mverb[0m [35mafterAdd[0m /root/.npm/minimist/0.0.8/p[K [[7m      [27m[90m............[0m] | fetchMetadata: [34;40mverb[0m [35mafterAdd[0m /root/.npm/minimist/0.0.8/p[K [[7m          [27m[90m........[0m] \ diffTrees: [7msill[0m [35minstall[0m generateActionsToTake[K [[7m             [27m[90m.....[0m] | fetch: [7msill[0m [35mdoParallel[0m fetch 12[K [[7m             [27m[90m.....[0m] | extract:homebridge: [7msill[0m [35mdoParallel[0m extract 12[K [[7m             [27m[90m.....[0m] / extract:homebridge: [7msill[0m [35mdoParallel[0m extract 12[K [[7m             [27m[90m.....[0m] \ extract:homebridge: [7msill[0m [35mdoParallel[0m extract 12[K [[7m             [27m[90m.....[0m] | extract:homebridge: [7msill[0m [35mdoParallel[0m extract 12[K [[7m             [27m[90m.....[0m] | extract:homebridge: [7msill[0m [35mdoParallel[0m extract 12[K [[7m             [27m[90m.....[0m] - extract:homebridge: [7msill[0m [35mdoParallel[0m extract 12[K [[7m             [27m[90m.....[0m] / extract:homebridge: [7msill[0m [35mdoParallel[0m extract 12[K [[7m             [27m[90m.....[0m] | extract:homebridge: [7msill[0m [35mdoParallel[0m extract 12[K [[7m             [27m[90m.....[0m] - extract:ip: [34;40mverb[0m [35mgentlyRm[0m don't care about contents; nuk[K [[7m             [27m[90m.....[0m] \ extract:curve25519-n2: [34;40mverb[0m [35mgentlyRm[0m don't care about co[K [[7m              [27m[90m....[0m] - extract:minimist: [34;40mverb[0m [35mgentlyRm[0m don't care about content[K [[7m              [27m[90m....[0m] | extract:debug: [7msill[0m [35mgunzTarPerm[0m modified mode [ 'CHANGEL[K [[7m              [27m[90m....[0m] | extract:homebridge: [34;40mverb[0m [35mgentlyRm[0m don't care about conte[K [[7m              [27m[90m....[0m] | extract:homebridge: [34;40mverb[0m [35mgentlyRm[0m don't care about conte[K [[7m               [27m[90m...[0m] - extract:nan: [34;40mverb[0m [35mgentlyRm[0m don't care about contents; nu[K [[7m               [27m[90m...[0m] | preinstall:homebridge: [7msill[0m [35mdoParallel[0m preinstall 12[K [[7m               [27m[90m...[0m] - finalize: [7msill[0m [35mfinalize[0m /usr/lib/node_modules/homebridge[K [[7m               [27m[90m...[0m] - finalize: [7msill[0m [35mfinalize[0m /usr/lib/node_modules/homebridge[K [[7m               [27m[90m...[0m] | finalize: [7msill[0m [35mfinalize[0m /usr/lib/node_modules/homebridge[K [K[?25h/usr/lib
2017-04-12 13:40:57	stdout	Updating Homebridge.
2017-04-12 13:40:57	stdout	Default env variables will be used.
2017-04-12 13:40:57	stdout	/root/.homebridge/.env not found.
2017-04-12 13:40:57	stdout	root
2017-04-12 13:40:57	stdout	Logged in as:```

**Comment by marcoraddatz** [comment]
@DaveHamilton Pease use latest version

**Comment by DaveHamilton** [comment]
@marcoraddatz thanks! That worked. I wish Docker would alert me when updates are available so I could've avoided bothering you. 😉

**Comment by marcoraddatz** [comment]
@DaveHamilton No problem. You might want to check out https://about.sibbell.com — it'll notify you about new releases.
