### ISSUE TITLE
homebridge -D can't run properly

### ISSUE THREAD

**Issue by Fetiz** [marcoraddatz/homebridge-docker#19]
when run ` homebridge -D ` , it always show some errors like this:

```bash
events.js:163                                                                                
      throw er; // Unhandled 'error' event                                                   
      ^                                                                                      
                                                                                             
Error: listen EADDRINUSE :::53699                                                            
    at Object.exports._errnoException (util.js:1050:11)                                      
    at exports._exceptionWithHostPort (util.js:1073:20)                                      
    at Server.setupListenHandle [as _listen2] (net.js:1263:14)                               
    at listenInCluster (net.js:1304:12)                                                      
    at Server.listen (net.js:1402:7)                                                         
    at EventedHTTPServer.listen (/usr/local/lib/node_modules/homebridge/node_modules/hap-node
js/lib/util/eventedhttp.js:60:19)                                                            
    at HAPServer.listen (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/H
APServer.js:158:20)                                                                          
    at Bridge.Accessory.publish (/usr/local/lib/node_modules/homebridge/node_modules/hap-node
js/lib/Accessory.js:509:16)                                                                  
    at Server._publish (/usr/local/lib/node_modules/homebridge/lib/server.js:114:16)         
    at Server.run (/usr/local/lib/node_modules/homebridge/lib/server.js:91:10)    
```

**Comment by deadbone** [comment]
Perhaps do you have a service in use on the same port ?

**Comment by Fetiz** [comment]
I have checked the 58619 is not occupied by others. and the docker is set use the same net with the diskstation.
