### ISSUE TITLE
Homebridge-Platform-Ring-Video-Doorbell

### ISSUE THREAD

**Issue by thechrisreese** [marcoraddatz/homebridge-docker#25]
Hello - I am running Homebridge-docker on a QNAP 451+ in Container and cannot get this plugin to load. I think its because it is run in a docker container but I don't know enough about this - where are the files loaded for node_modules or how I can fix this. When I look up usr/local/lib/node_modules/homebridge-platform-ring-video-doorbell/node_modules/pcap2/ it says the director does not exist. 

It is throwing this error:

�ERROR LOADING PLUGIN homebridge-platform-ring-video-doorbell:
[2017-9-3 23:17:45] Error: Cannot find module './build/Release/pcap_binding'
at Function.Module._resolveFilename (module.js:485:15)
at Function.Module._load (module.js:437:25)
at Module.require (module.js:513:17)
at require (internal/module.js:11:18)
at Object. (/usr/local/lib/node_modules/homebridge-platform-ring-video-doorbell/node_modules/pcap2/index.js:6:22)
at Module._compile (module.js:569:30)
at Object.Module._extensions..js (module.js:580:10)
at Module.load (module.js:503:32)
at tryModuleLoad (module.js:466:12)
at Function.Module._load (module.js:458:3)

**Comment by deadbone** [comment]
Hi sometimes I get this error with the module "commander"
So, in the install.sh, I do : npm install -gs commander

Perhaps could you try the samething with your missing module ?
npm install -gs pcap_binding

**Comment by thechrisreese** [comment]
I’ll try. Thanks!

**Comment by deadbone** [comment]
so ? all's good ?

**Comment by thechrisreese** [comment]
@deadbone nope. Cant get it to work. Don’t know where files are saved to either. All sorts of broken.

**Comment by deadbone** [comment]
files are saved in your container

**Comment by marcoraddatz** [comment]
Seems to be non-Homebridge related.
