### ISSUE TITLE
Problem Setting Up Amazon Dash Buttons

### ISSUE THREAD

**Issue by V3L** [marcoraddatz/homebridge-docker#54]
Hi,

I've been using homebridge-docker for sometime now without any issues, however I recently tried adding https://github.com/KhaosT/homebridge-amazondash to my setup so I can use an amazon dash button to trigger some scenes in my homekit setup.

To get this working I've added the following to my install.sh file:
apt-get -y install libpcap-dev
npm install -gs node-dash-button
npm install -gs homebridge-amazondash

Then when I try to add a button to my config.json file, I keep getting the following error:
`/usr/local/lib/node_modules/homebridge/lib/api.js:122
      throw new Error("The requested platform '" + name + "' was not registered by any plugin.");
      ^
Error: The requested platform 'AmazonDash' was not registered by any plugin.
    at API.platform (/usr/local/lib/node_modules/homebridge/lib/api.js:122:13)
    at Server._loadPlatforms (/usr/local/lib/node_modules/homebridge/lib/server.js:315:45)
    at Server.run (/usr/local/lib/node_modules/homebridge/lib/server.js:85:36)
    at module.exports (/usr/local/lib/node_modules/homebridge/lib/cli.js:43:10)
    at Object.<anonymous> (/usr/local/lib/node_modules/homebridge/bin/homebridge:17:22)
    at Module._compile (module.js:649:30)
    at Object.Module._extensions..js (module.js:660:10)
    at Module.load (module.js:561:32)
    at tryModuleLoad (module.js:501:12)
    at Function.Module._load (module.js:493:3)
    at Function.Module.runMain (module.js:690:10)
    at startup (bootstrap_node.js:194:16)
    at bootstrap_node.js:666:3`

The button is added to my config.json like:
`
{
      "platform": "AmazonDash",
      "buttons": [
      {
        "name": "Cupboard Dash",
        "mac": "6c:56:97:06:ef:55"
      }
    ]
   }
`

Do you have any ideas what could be causing this, or what I need to do to resolve the issue?

**Comment by marcoraddatz** [comment]
Seems like the plugin cannot be found. Have you restarted the container after adding the dash button to your config? I don't know any other things to try.
